import React, { useState, useEffect, useCallback } from "react";
import { useAuth } from "../context/AuthContext";
import "./AdminReports.css";
import axios from "axios";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const api = axios.create({
  baseURL: "http://localhost:5000/api",
  timeout: 15000,
});

api.interceptors.request.use((config) => {
  const token = localStorage.getItem("token");
  if (token) {
    config.headers.Authorization = `Bearer ${token}`;
  }
  return config;
});

const AdminReports = () => {
  const { user } = useAuth();

  const [reports, setReports] = useState({
    totalUsers: 0,
    activeUsers: 0,
    totalComplaints: 0,
    resolvedComplaints: 0,
    pendingComplaints: 0,
    newUsersThisRange: 0,
    complaintResolutionRate: 0,
    userGrowth: [],
    complaintTrends: [],
    systemMetrics: {},
    lastUpdated: null,
  });

  const [loading, setLoading] = useState(true);
  const [timeRange, setTimeRange] = useState("month");
  const [selectedReport, setSelectedReport] = useState("overview");
  const [error, setError] = useState(null);
  const [pdfLoading, setPdfLoading] = useState(false);

  const getLargestPercentage = (data) => {
    if (!data || typeof data !== "object") return null;

    const entries = Object.entries(data);
    const total = entries.reduce((sum, [, v]) => sum + (Number(v) || 0), 0);

    if (total === 0) return null;

    let maxPercent = 0;
    let maxLabel = "";

    entries.forEach(([key, value]) => {
      const percent = (Number(value) / total) * 100;
      if (percent > maxPercent) {
        maxPercent = percent;
        maxLabel = key;
      }
    });

    return { label: maxLabel, percent: maxPercent.toFixed(1) };
  };

  const fetchReportsData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await api.get(`/admin/reports?range=${timeRange}`);
      const data = res.data && res.data.success ? res.data : res.data || {};

      const mapped = {
        totalUsers: Number(data.totalUsers ?? 0),
        activeUsers: Number(data.activeUsers ?? data.totalUsers ?? 0),
        totalComplaints: Number(data.totalComplaints ?? 0),
        resolvedComplaints: Number(data.resolvedComplaints ?? 0),
        pendingComplaints: Number(data.pendingComplaints ?? 0),
        newUsersThisRange: Number(
          data.newUsersThisRange ?? data.newUsersThisMonth ?? 0
        ),
        complaintResolutionRate: Number(data.complaintResolutionRate ?? 0),
        userGrowth: Array.isArray(data.userGrowth) ? data.userGrowth : [],
        complaintTrends: Array.isArray(data.complaintTrends)
          ? data.complaintTrends
          : [],
        systemMetrics: data.systemMetrics ?? {},
        issueStatusCounts:
          typeof data.issueStatusCounts === "object" &&
          data.issueStatusCounts !== null
            ? data.issueStatusCounts
            : { reported: 0, "in progress": 0, resolved: 0, rejected: 0 },
        priorityCounts:
          typeof data.priorityCounts === "object" &&
          data.priorityCounts !== null
            ? data.priorityCounts
            : { high: 0, medium: 0, low: 0 },
        lastUpdated: new Date().toISOString(),
      };

      setReports(mapped);
    } catch (err) {
      console.error("Failed to load reports:", err);
      setError("Failed to load reports. Check console for details.");
    } finally {
      setLoading(false);
    }
  }, [timeRange]);

  const exportToPDF = async () => {
    setPdfLoading(true);
    try {
      const doc = new jsPDF();
      
      doc.setFillColor(59, 130, 246);
      doc.rect(0, 0, doc.internal.pageSize.getWidth(), 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.text("ADMIN ANALYTICS REPORT", 105, 20, { align: 'center' });
      doc.setFontSize(12);
      doc.text("Community Issues Resolution System", 105, 30, { align: 'center' });
      
      doc.setTextColor(0, 0, 0);
      
      let yPosition = 55;

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, yPosition);
      doc.text(`Time Range: ${getTimeRangeLabel(timeRange)}`, 14, yPosition + 6);
      doc.text(`Generated by: ${user?.name || 'Admin'}`, 14, yPosition + 12);
      
      yPosition += 25;

      doc.setFontSize(16);
      doc.setTextColor(31, 41, 55);
      doc.text("KEY METRICS OVERVIEW", 14, yPosition);
      yPosition += 10;

      const metricsData = [
        ['Total Users', reports.totalUsers.toLocaleString()],
        ['Active Users', reports.activeUsers.toLocaleString()],
        ['User Engagement Rate', `${userEngagementRate}%`],
        ['New Users', reports.newUsersThisRange.toLocaleString()],
        ['Total Complaints', reports.totalComplaints.toLocaleString()],
        ['Resolved Complaints', reports.resolvedComplaints.toLocaleString()],
        ['Pending Complaints', reports.pendingComplaints.toLocaleString()],
        ['Resolution Rate', `${reports.complaintResolutionRate}%`]
      ];

      autoTable(doc, {
        startY: yPosition,
        head: [['Metric', 'Value']],
        body: metricsData,
        theme: 'grid',
        headStyles: { fillColor: [59, 130, 246] },
        styles: { fontSize: 10, cellPadding: 3 },
        margin: { left: 14, right: 14 }
      });

      yPosition = doc.lastAutoTable.finalY + 15;

      doc.setFontSize(16);
      doc.setTextColor(31, 41, 55);
      doc.text("SYSTEM PERFORMANCE", 14, yPosition);
      yPosition += 10;

      const performanceData = [
        ['Average Response Time', reports.systemMetrics.avgResponseTime || 'N/A'],
        ['User Satisfaction', reports.systemMetrics.userSatisfaction || 'N/A'],
        ['System Uptime', reports.systemMetrics.systemUptime || 'N/A'],
        ['Active Sessions', reports.systemMetrics.activeSessions || 'N/A']
      ];

      autoTable(doc, {
        startY: yPosition,
        head: [['Metric', 'Value']],
        body: performanceData,
        theme: 'grid',
        headStyles: { fillColor: [34, 197, 94] },
        styles: { fontSize: 10, cellPadding: 3 },
        margin: { left: 14, right: 14 }
      });

      yPosition = doc.lastAutoTable.finalY + 15;

      doc.addPage();
      yPosition = 20;

      doc.setFontSize(16);
      doc.setTextColor(31, 41, 55);
      doc.text("ISSUE STATUS DISTRIBUTION", 14, yPosition);
      yPosition += 10;

      const statusEntries = Object.entries(reports.issueStatusCounts || {});
      const statusTotal = statusEntries.reduce((sum, [, count]) => sum + (Number(count) || 0), 0);
      
      const statusData = statusEntries.map(([status, count]) => [
        status.charAt(0).toUpperCase() + status.slice(1),
        count,
        statusTotal > 0 ? `${((count / statusTotal) * 100).toFixed(1)}%` : '0%'
      ]);

      autoTable(doc, {
        startY: yPosition,
        head: [['Status', 'Count', 'Percentage']],
        body: statusData,
        theme: 'grid',
        headStyles: { fillColor: [139, 69, 19] },
        styles: { fontSize: 10, cellPadding: 3 },
        margin: { left: 14, right: 14 }
      });

      yPosition = doc.lastAutoTable.finalY + 15;

      doc.setFontSize(16);
      doc.setTextColor(31, 41, 55);
      doc.text("PRIORITY DISTRIBUTION", 14, yPosition);
      yPosition += 10;

      const priorityEntries = Object.entries(reports.priorityCounts || {});
      const priorityTotal = priorityEntries.reduce((sum, [, count]) => sum + (Number(count) || 0), 0);
      
      const priorityData = priorityEntries.map(([priority, count]) => [
        priority.charAt(0).toUpperCase() + priority.slice(1),
        count,
        priorityTotal > 0 ? `${((count / priorityTotal) * 100).toFixed(1)}%` : '0%'
      ]);

      autoTable(doc, {
        startY: yPosition,
        head: [['Priority', 'Count', 'Percentage']],
        body: priorityData,
        theme: 'grid',
        headStyles: { fillColor: [234, 88, 12] },
        styles: { fontSize: 10, cellPadding: 3 },
        margin: { left: 14, right: 14 }
      });

      yPosition = doc.lastAutoTable.finalY + 15;

      if (reports.userGrowth.length > 0) {
        doc.setFontSize(16);
        doc.setTextColor(31, 41, 55);
        doc.text("USER GROWTH TREND", 14, yPosition);
        yPosition += 10;

        const growthData = reports.userGrowth.map(item => [
          item.month,
          item.users
        ]);

        autoTable(doc, {
          startY: yPosition,
          head: [['Month', 'Users']],
          body: growthData,
          theme: 'grid',
          headStyles: { fillColor: [147, 51, 234] },
          styles: { fontSize: 10, cellPadding: 3 },
          margin: { left: 14, right: 14 }
        });

        yPosition = doc.lastAutoTable.finalY + 15;
      }

      if (reports.complaintTrends.length > 0) {
        if (yPosition > 200) {
          doc.addPage();
          yPosition = 20;
        }

        doc.setFontSize(16);
        doc.setTextColor(31, 41, 55);
        doc.text("COMPLAINT CATEGORIES", 14, yPosition);
        yPosition += 10;

        const complaintData = reports.complaintTrends.map(item => [
          item.category,
          item.count
        ]);

        autoTable(doc, {
          startY: yPosition,
          head: [['Category', 'Count']],
          body: complaintData,
          theme: 'grid',
          headStyles: { fillColor: [219, 39, 119] },
          styles: { fontSize: 10, cellPadding: 3 },
          margin: { left: 14, right: 14 }
        });
      }

      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        doc.text(
          `Page ${i} of ${pageCount} • Generated by Community Issues Resolution System`,
          doc.internal.pageSize.getWidth() / 2,
          doc.internal.pageSize.getHeight() - 10,
          { align: 'center' }
        );
      }

      const fileName = `admin-report-${getTimeRangeLabel(timeRange).toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`;
      doc.save(fileName);

    } catch (error) {
      console.error('Error generating PDF:', error);
      alert('Failed to generate PDF report. Please try again.');
    } finally {
      setPdfLoading(false);
    }
  };

  const getTimeRangeLabel = (range) => {
    const labels = {
      week: 'Last 7 Days',
      month: 'Last 30 Days',
      quarter: 'Last Quarter',
      year: 'Last Year'
    };
    return labels[range] || range;
  };

  const exportReport = (format) => {
    if (format === "pdf") {
      exportToPDF();
      return;
    }

    if (format === "csv") {
      const rows = [
        ["metric", "value"],
        ["totalUsers", reports.totalUsers],
        ["activeUsers", reports.activeUsers],
        ["totalComplaints", reports.totalComplaints],
        ["resolvedComplaints", reports.resolvedComplaints],
        ["pendingComplaints", reports.pendingComplaints],
        ["newUsersThisRange", reports.newUsersThisRange],
        ["complaintResolutionRate", reports.complaintResolutionRate],
      ];
      const csvContent = rows.map((r) => r.join(",")).join("\n");
      const blob = new Blob([csvContent], { type: "text/csv" });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `admin_report_${new Date().toISOString().split("T")[0]}.csv`;
      a.click();
      window.URL.revokeObjectURL(url);
      return;
    }

    const dataStr = JSON.stringify(reports, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `admin_report_${new Date().toISOString().split("T")[0]}.json`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const buildDonut = (data = {}, colors = []) => {
    if (!data || typeof data !== "object") {
      return "conic-gradient(#eee 0deg 360deg)";
    }

    const entries = Object.entries(data || {});
    const total = entries.reduce((sum, [, v]) => sum + (Number(v) || 0), 0);

    if (total === 0) {
      return "conic-gradient(#eee 0deg 360deg)";
    }

    let start = 0;
    const gradientParts = entries.map(([key, value], i) => {
      const val = Number(value) || 0;
      const percent = (val / total) * 100;
      const color = colors[i % colors.length] || "#ccc";
      const seg = `${color} ${start}% ${start + percent}%`;
      start += percent;
      return seg;
    });

    return `conic-gradient(${gradientParts.join(", ")})`;
  };

  useEffect(() => {
    let mounted = true;

    const load = async () => {
      if (user && ["admin", "globaladmin"].includes(user.role)) {
        if (mounted) await fetchReportsData();
      } else {
        if (mounted) setLoading(false);
      }
    };

    load();

    return () => {
      mounted = false;
    };
  }, [user, timeRange, fetchReportsData]);

  const userEngagementRate =
    reports.totalUsers > 0
      ? Math.round((reports.activeUsers / reports.totalUsers) * 100)
      : 0;

  if (!user || !["admin", "globaladmin"].includes(user.role)) {
    return (
      <div className="admin-reports">
        <div className="container">
          <div className="not-authorized">
            <h2>Access Denied</h2>
            <p>You must be an administrator to access this page.</p>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="admin-reports">
        <div className="container">
          <div className="loading">
            <div className="loading-spinner"></div>
            Loading reports data...
          </div>
        </div>
      </div>
    );
  }

  const largestPriority = getLargestPercentage(reports.priorityCounts);
  const largestStatus = getLargestPercentage(reports.issueStatusCounts);
  
  return (
    <div className="admin-reports">
      <div className="container">
        <div className="reports-header">
          <div className="header-content">
            <h1>Analytics & Reports</h1>
            <p>View system analytics and generate detailed reports (live)</p>
          </div>
          <div className="header-actions">
            <button
              className="btn export-primary"
              onClick={() => exportReport("pdf")}
              disabled={pdfLoading}
            >
              <span className="btn-icon">
                <i className="bi bi-file-pdf"></i>
              </span>
              {pdfLoading ? "Generating PDF..." : "Export PDF"}
            </button>
            <button
              className="btn export-secondary"
              onClick={() => exportReport("json")}
            >
              <span className="btn-icon">
                <i className="bi bi-download"></i>
              </span>
              Export JSON
            </button>
          </div>
        </div>

        {error ? (
          <div className="section">
            <h3>Error</h3>
            <p style={{ color: "red" }}>{error}</p>
          </div>
        ) : null}

        <div className="section">
          <h2>Key Metrics</h2>
          <div className="metrics-grid">
            <div className="metric-card">
              <div className="metric-icon">
                <span>
                  <i className="bi bi-people"></i>
                </span>
              </div>
              <div className="metric-content">
                <h3>Total Users</h3>
                <p className="metric-value">
                  {reports.totalUsers.toLocaleString()}
                </p>
                <p className="metric-change positive">
                  <strong>New This Range:</strong> {reports.newUsersThisRange}
                </p>
              </div>
            </div>

            <div className="metric-card">
              <div className="metric-icon">
                <span>
                  <i className="bi bi-person-check"></i>
                </span>
              </div>
              <div className="metric-content">
                <h3>Active Users</h3>
                <p className="metric-value">
                  {reports.activeUsers.toLocaleString()}
                </p>
                <p className="metric-subtitle">
                  {userEngagementRate}% engagement rate
                </p>
              </div>
            </div>

            <div className="metric-card">
              <div className="metric-icon">
                <span>
                  <i className="bi bi-exclamation-triangle"></i>
                </span>
              </div>
              <div className="metric-content">
                <h3>Total Complaints</h3>
                <p className="metric-value">
                  {reports.totalComplaints.toLocaleString()}
                </p>
                <p className="metric-subtitle">
                  {reports.pendingComplaints} pending resolution
                </p>
              </div>
            </div>

            <div className="metric-card">
              <div className="metric-icon">
                <span>
                  <i className="bi bi-bullseye"></i>
                </span>
              </div>
              <div className="metric-content">
                <h3>Resolution Rate</h3>
                <p className="metric-value">
                  {reports.complaintResolutionRate}%
                </p>
                <p className="metric-change positive">
                  {reports.resolvedComplaints} resolved •{" "}
                  {reports.systemMetrics.avgResponseTime ?? "—"} avg
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="section">
          <div className="section-header">
            <div>
              <h2>Reporting Dashboard</h2>
              <p>Live analytics and performance metrics</p>
            </div>
            <div className="time-range-selector">
              <label htmlFor="timeRange">Time Range:</label>
              <select
                id="timeRange"
                value={timeRange}
                onChange={(e) => setTimeRange(e.target.value)}
              >
                <option value="week">Last 7 Days</option>
                <option value="month">Last 30 Days</option>
                <option value="quarter">Last Quarter</option>
                <option value="year">Last Year</option>
              </select>
            </div>
          </div>

          <div className="dashboard-grid">
            <div className="charts-section">
              <div className="chart-card large">
                <div className="chart-header">
                  <h4>User Growth Trend</h4>
                  <div className="chart-actions">
                    <span className="data-info">
                      {reports.userGrowth.length} months data
                    </span>
                    <button
                      className="btn btn-outline"
                      onClick={fetchReportsData}
                    >
                      <i className="bi bi-arrow-clockwise"></i>
                      Refresh Data
                    </button>
                  </div>
                </div>
                <div className="chart-placeholder">
                  <div className="data-chart">
                    <div className="chart-bars">
                      {reports.userGrowth.length === 0 ? (
                        <div style={{ color: "#163832" }}>
                          No user growth data
                        </div>
                      ) : (
                        reports.userGrowth.map((item, index) => {
                          const max = Math.max(
                            ...reports.userGrowth.map((g) => g.users),
                            1
                          );
                          const heightPct = ((item.users || 0) / max) * 80;
                          return (
                            <div key={index} className="chart-bar-container">
                              <div
                                className="chart-bar"
                                style={{ height: `${heightPct}px` }}
                                title={`${item.month}: ${item.users} users`}
                              >
                                <div className="chart-bar-value">
                                  {item.users}
                                </div>
                              </div>
                              <span className="chart-label">{item.month}</span>
                            </div>
                          );
                        })
                      )}
                    </div>
                    <p className="chart-description">
                      User growth over {reports.userGrowth.length} months
                    </p>
                  </div>
                </div>
              </div>

              <div className="pie-charts-wrapper">
                <div className="pie-card">
                  <h4>Issue Status Distribution</h4>

                  <div
                    className="donut"
                    style={{
                      background: buildDonut(reports.issueStatusCounts, [
                        "#051f20",
                        "#235347",
                        "#daf1de",
                        "#9E9E9E",
                      ]),
                    }}
                  >
                    {largestStatus && (
                      <div className="donut-center-content">
                        <span className="donut-percent">
                          {largestStatus.percent}%
                        </span>
                        <span className="donut-label">
                          {largestStatus.label}
                        </span>
                      </div>
                    )}
                  </div>

                  <div className="donut-legend">
                    {Object.entries(reports.issueStatusCounts || {}).map(
                      ([label, value], i) => {
                        const statusTotal = Object.values(
                          reports.issueStatusCounts || {}
                        ).reduce((a, b) => a + b, 0);

                        const percent =
                          statusTotal > 0
                            ? ((value / statusTotal) * 100).toFixed(1)
                            : 0;

                        const colors = [
                          "#051f20",
                          "#235347",
                          "#daf1de",
                          "#9E9E9E",
                        ];

                        return (
                          <div key={i} className="legend-row">
                            <span
                              className="legend-color"
                              style={{ background: colors[i] }}
                            ></span>
                            <span className="legend-text">
                              {label} — <strong>{value}</strong> ({percent}%)
                            </span>
                          </div>
                        );
                      }
                    )}
                  </div>
                </div>

                <div className="pie-card">
                  <h4>Priority Distribution</h4>

                  <div
                    className="donut"
                    style={{
                      background: buildDonut(reports.priorityCounts, [
                        "#051f20",
                        "#235347",
                        "#daf1de",
                      ]),
                    }}
                  >
                    {largestPriority && (
                      <div className="donut-center-content">
                        <span className="donut-percent">
                          {largestPriority.percent}%
                        </span>
                        <span className="donut-label">
                          {largestPriority.label}
                        </span>
                      </div>
                    )}
                  </div>

                  <div className="donut-legend">
                    {Object.entries(reports.priorityCounts || {}).map(
                      ([key, value], idx) => {
                        const priorityTotal = Object.values(
                          reports.priorityCounts || {}
                        ).reduce((a, b) => a + b, 0);

                        const percent =
                          priorityTotal > 0
                            ? ((value / priorityTotal) * 100).toFixed(1)
                            : 0;

                        const colors = ["#051f20", "#235347", "#daf1de"];

                        return (
                          <div className="legend-row" key={key}>
                            <span
                              className="legend-color"
                              style={{
                                background: colors[idx],
                              }}
                            ></span>

                            <span className="legend-text">
                              {key} — <strong>{value}</strong> ({percent}%)
                            </span>
                          </div>
                        );
                      }
                    )}
                  </div>
                </div>
              </div>
            </div>

            <div className="reports-sidebar">
              <div className="sidebar-card">
                <h5>System Performance</h5>
                <div className="stats-list">
                  <div className="stat-item">
                    <span className="stat-label">Avg. Response Time</span>
                    <span className="stat-value">
                      {reports.systemMetrics.avgResponseTime ?? "—"}
                    </span>
                  </div>
                  <div className="stat-item">
                    <span className="stat-label">User Satisfaction</span>
                    <span className="stat-value">
                      {reports.systemMetrics.userSatisfaction ?? "—"}
                    </span>
                  </div>
                  <div className="stat-item">
                    <span className="stat-label">System Uptime</span>
                    <span className="stat-value">
                      {reports.systemMetrics.systemUptime ?? "—"}
                    </span>
                  </div>
                  <div className="stat-item">
                    <span className="stat-label">Active Sessions</span>
                    <span className="stat-value">
                      {reports.systemMetrics.activeSessions ?? "—"}
                    </span>
                  </div>
                </div>
              </div>

              <div className="sidebar-card">
                <h5>Generate Reports</h5>
                <div className="action-buttons">
                  <button
                    className="actionss-btn"
                    onClick={() => exportReport("pdf")}
                    disabled={pdfLoading}
                  >
                    <span className="action-icon">
                      <i className="bi bi-file-pdf"></i>
                    </span>
                    {pdfLoading ? "Generating..." : "PDF Report"}
                  </button>
                  <button
                    className="actionss-btn"
                    onClick={() => exportReport("json")}
                  >
                    <span className="action-icon">
                      <i className="bi bi-clipboard2-data"></i>
                    </span>
                    JSON Report
                  </button>
                  <button
                    className="actionss-btn"
                    onClick={() => exportReport("csv")}
                  >
                    <span className="action-icon">
                      <i className="bi bi-pass"></i>
                    </span>
                    CSV Export
                  </button>
                  <button className="actionss-btn" onClick={fetchReportsData}>
                    <span className="action-icon">
                      <i className="bi bi-arrow-clockwise"></i>
                    </span>
                    Refresh Data
                  </button>
                </div>
              </div>

              <div className="sidebar-card">
                <h5>Data Status</h5>
                <div className="status-list">
                  <div className="status-item">
                    <span className="status-label">Data Source</span>
                    <span className="status-value">Live Backend</span>
                  </div>
                  <div className="status-item">
                    <span className="status-label">Last Updated</span>
                    <span className="status-value">
                      {reports.lastUpdated
                        ? new Date(reports.lastUpdated).toLocaleString()
                        : new Date().toLocaleString()}
                    </span>
                  </div>
                  <div className="status-item">
                    <span className="status-label">Time Range</span>
                    <span className="status-value">{timeRange}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="chart-card full-width">
            <h4>Complaint Distribution</h4>
            <div className="chart-placeholder">
              <div className="data-chart">
                <div className="complaint-categories">
                  {reports.complaintTrends.length === 0 ? (
                    <div style={{ color: "#163832" }}>No complaint trends</div>
                  ) : (
                    reports.complaintTrends.map((item, index) => (
                      <div key={index} className="category-item">
                        <span className="category-name">{item.category}</span>
                        <span className="category-count">{item.count}</span>
                      </div>
                    ))
                  )}
                </div>
                <p className="chart-description">
                  {reports.complaintTrends.length} complaint categories
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="section">
          <h3>Data Summary</h3>
          <div className="data-summary">
            <div className="summary-card">
              <h4>User Statistics</h4>
              <div className="summary-content">
                <p>
                  <strong>Total Registered:</strong>{" "}
                  {reports.totalUsers.toLocaleString()}
                </p>
                <p>
                  <strong>Currently Active:</strong>{" "}
                  {reports.activeUsers.toLocaleString()}
                </p>
                <p>
                  <strong>New This Range:</strong> {reports.newUsersThisRange}
                </p>
                <p>
                  <strong>Engagement Rate:</strong> {userEngagementRate}%
                </p>
              </div>
            </div>

            <div className="summary-card">
              <h4>Complaint Analytics</h4>
              <div className="summary-content">
                <p>
                  <strong>Total Complaints:</strong>{" "}
                  {reports.totalComplaints.toLocaleString()}
                </p>
                <p>
                  <strong>Resolved:</strong>{" "}
                  {reports.resolvedComplaints.toLocaleString()}
                </p>
                <p>
                  <strong>Pending:</strong>{" "}
                  {reports.pendingComplaints.toLocaleString()}
                </p>
                <p>
                  <strong>Resolution Rate:</strong>{" "}
                  {reports.complaintResolutionRate}%
                </p>
              </div>
            </div>

            <div className="summary-card">
              <h4>System Health</h4>
              <div className="summary-content">
                <p>
                  <strong>Avg Response Time:</strong>{" "}
                  {reports.systemMetrics.avgResponseTime ?? "—"}
                </p>
                <p>
                  <strong>User Satisfaction:</strong>{" "}
                  {reports.systemMetrics.userSatisfaction ?? "—"}
                </p>
                <p>
                  <strong>System Uptime:</strong>{" "}
                  {reports.systemMetrics.systemUptime ?? "—"}
                </p>
                <p>
                  <strong>Active Sessions:</strong>{" "}
                  {reports.systemMetrics.activeSessions ?? "—"}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminReports;
